### ISSUE TITLE
show mgmt frontend adapter all is not working when rollback with commit id.

### ISSUE THREAD

**Issue by gpnaveen** [pushpasis/frr#67]
Build - Oct 26

Steps: follow the records.

oot@frr:~# /usr/lib/frr/frrinit.sh stop
 * Stopped watchfrr
 * Stopped mgmtd
 * Stopped staticd
 * Stopped zebra
root@frr:~# ls /var/lib/systemd/coredump/
root@frr:~# /usr/lib/frr/frrinit.sh start
 * Started watchfrr
root@frr:~# vtysh 

Hello, this is FRRouting (version 8.2-dev-MyDebPkgVersion).
Copyright 1996-2005 Kunihiro Ishiguro, et al.

frr# 
frr# 
frr# 
frr# conf t
frr(config)# do show run 
Building configuration...

Current configuration:
!
frr version 8.2-dev-MyDebPkgVersion
frr defaults traditional
hostname frr
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config
!
ip route 1.1.1.100/32 Null0
!
end
frr(config)# do ip route 1.1.1.100/32 Null0
% Unknown command: do ip route 1.1.1.100/32 Null0
frr(config)# ip route 123.123.123.123/32 Null0
frr(config)# ip route 1.1.1.100/32 Null0
frr(config)# ip route 123.123.123.123/32 Null0
frr(config)# end
frr# show run 
Building configuration...

Current configuration:
!
frr version 8.2-dev-MyDebPkgVersion
frr defaults traditional
hostname frr
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config
!
ip route 1.1.1.100/32 Null0
ip route 123.123.123.123/32 Null0
!
end
frr# show mgmt commit-history 
Last 10 commit history:
  Sl.No Commit-ID(HEX)                    Commit-Record-Time
  0     37a9b0bdf14744a6e3e8b16dde41f319  2021-10-26 16:29:10.480728
  1     95fd286716fcb26fbc95eb7539a71529  2021-10-20 16:37:58.724532
frr# show mgmt commit-history 
Last 10 commit history:
  Sl.No Commit-ID(HEX)                    Commit-Record-Time
  0     37a9b0bdf14744a6e3e8b16dde41f319  2021-10-26 16:29:10.480728
  1     95fd286716fcb26fbc95eb7539a71529  2021-10-20 16:37:58.724532
frr# conf t
frr(config)# mgmt rollback commit-id 
  WORD  Commit-ID
frr(config)# mgmt rollback commit-id 95fd286716fcb26fbc95eb7539a71529
frr(config)# do show mgmt commit-history 
Last 10 commit history:
  Sl.No Commit-ID(HEX)                    Commit-Record-Time
  0     95fd286716fcb26fbc95eb7539a71529  2021-10-20 16:37:58.724532
frr(config)# mgmt rollback commit-id 95fd286716fcb26fbc95eb7539a71529
Error with creating commit apply trxn with error code -1
frr(config)# mgmt rollback commit-id 95fd286716fcb26fbc95eb7539a71529
Error with creating commit apply trxn with error code -1
frr(config)# mgmt rollback commit-id 95fd286716fcb26fbc95eb7539a71529
Error with creating commit apply trxn with error code -1
frr(config)# do show mgmt commit-history 
Last 10 commit history:
  Sl.No Commit-ID(HEX)                    Commit-Record-Time
  0     95fd286716fcb26fbc95eb7539a71529  2021-10-20 16:37:58.724532
frr(config)# end
frr# conf t
ERROR: Locking for DB 2 failed! Err: 'Lock already taken on DB by another session!'
frr# show mgmt 
  backend-adapter              MGMTD Backend Adapter information
  backend-yang-xpath-registry  Backend Adapter YANG Xpath Registry
  commit-history               Show commit history
  database                     MGMTD Database information
  database-contents            Get Database contents from a specific database
  frontend-adapter             MGMTD Frontend Adapter information
  get-config                   Get configuration data from a specific configuration database
  get-data                     Get data from a specific database
  transaction                  MGMTD Transaction information
  yang-xpath-subscription      Get YANG Backend Subscription
frr# show mgmt frontend-adapter 
  all  Display all Frontend Adapters
frr# show mgmt frontend-adapter all 
  <cr>    
  detail  Details of commit stats
frr# show mgmt frontend-adapter all detail 
% [MGMTD] Unknown command: show mgmt frontend-adapter all detail 
frr# show mgmt frontend-adapter all detail 
% [MGMTD] Unknown command: show mgmt frontend-adapter all detail 
frr# show mgmt frontend-adapter all detail 
% [MGMTD] Unknown command: show mgmt frontend-adapter all detail 
frr# show mgmt frontend-adapter all detail 
% [MGMTD] Unknown command: show mgmt frontend-adapter all detail 
frr#

**Comment by pushpasis** [comment]
@gpnaveen This is fixed already. Closing it.
