### ISSUE TITLE
mgmtd crashed when show mgmt get-config cmd is used.

### ISSUE THREAD

**Issue by gpnaveen** [pushpasis/frr#75]
Build Oct 27: 

frr# show run 
Building configuration...

Current configuration:
!
frr version 8.2-dev-MyDebPkgVersion
frr defaults traditional
hostname frr
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config
!
ip route 192.1.1.1/32 Null0
!
end
frr# exit

root@frr:/home/naveen/ci/mgmt_auto/frr/tests/topotests/yang_mgmt# /usr/lib/frr/frrinit.sh stop
 * Stopped watchfrr
 * Cannot stop mgmtd: pid 7690 not running
 * Stopped staticd
 * Stopped zebra
root@frr:/home/naveen/ci/mgmt_auto/frr/tests/topotests/yang_mgmt# /usr/lib/frr/frrinit.sh start
 * Started watchfrr
root@frr:/home/naveen/ci/mgmt_auto/frr/tests/topotests/yang_mgmt# vtysh

Hello, this is FRRouting (version 8.2-dev-MyDebPkgVersion).
Copyright 1996-2005 Kunihiro Ishiguro, et al.

frr# conf t
frr(config)# log file 
  FILENAME  Logging filename
frr(config)# log file mgmt.log 
  <cr>           
  alerts         Immediate action needed
  critical       Critical conditions
  debugging      Debugging messages
  emergencies    System is unusable
  errors         Error conditions
  informational  Informational messages
  notifications  Normal but significant conditions
  warnings       Warning conditions
frr(config)# log file mgmt.log 
can't open logfile mgmt.log
frr(config)# log file /tmp/mgmt.log 
frr(config)# end
frr# debg 
% There is no matched command.
frr# debug 
  babel             Babel information
  bfd               Bidirection Forwarding Detection
  bgp               BGP information
  eigrp             EIGRP information
  igmp              IGMP protocol activity
  isis              IS-IS routing protocol
  memstats-at-exit  Print memory statistics at exit
  mgmt              Management Daemon (MGMTD) information
  mpls              MPLS information
  mroute            PIM interaction with kernel MFC cache
  msdp              MSDP protocol activity
  mtrace            Mtrace protocol activity
  nhrp              NHRP information
  northbound        Northbound debugging
  openfabric        OpenFabric routing protocol
  ospf              OSPF information
  ospf6             Open Shortest Path First (OSPF) for IPv6
  pathd             path debugging
  pbr               Policy Based Routing
  pim               PIM protocol activity
  prefix-list       Prefix-list test access
  resolver          Debug DNS resolver actions
  rfapi-dev         RF API debugging/testing command
  rip               RIP information
  ripng             RIPng configuration
  route-map         Debug option set for route-maps
  rpki              Enable debugging for rpki
  spf-delay-ietf    SPF Back-off Debugging
  ssmpingd          ssmpingd activity
  static            Static route daemon
  vrf               VRF Debugging
  vrrp              Virtual Router Redundancy Protocol
  zebra             Zebra configuration
frr# debug mgmt 
  all          Debug All Functionality
  backend      Debug Backend Functionality
  database     Debug Database Functionality
  frontend     Debug Frontend Functionality
  transaction  Debug Transaction Functionality
frr# debug mgmt all
frr# conf t
frr(config)# show mgmt get-config xpath /frr-routing:routing/control-plane-protocols/control-plane-protocol[type='frr-staticd:staticd'
% Unknown command: show mgmt get-config xpath /frr-routing:routing/control-plane-protocols/control-plane-protocol[type='frr-staticd:staticd'
frr(config)# do show mgmt get-config xpath /frr-routing:routing/control-plane-protocols/control-plane-protocol[type='frr-staticd:staticd'
vtysh: error reading from mgmtd: Success (0)Warning: closing connection to mgmtd because of an I/O error!
frr(config)# end
Warning: connecting to mgmtd...failed!
frr# exit
Warning: connecting to mgmtd...failed!
root@frr:/home/naveen/ci/mgmt_auto/frr/tests/topotests/yang_mgmt# cat /tmp/mgmt.log 
2021/10/27 16:01:09 MGMTD: [Y3TVX-KE7HN] Unlocked DB 2 successfully!
2021/10/27 16:01:23 MGMTD: [SD07F-GYBSK] mgmt_frntnd_adapter_read: Got 22 bytes of message from MGMTD Frontend adapter 'mgmtd-7805'
2021/10/27 16:01:23 MGMTD: [SD07F-GYBSK] mgmt_frntnd_adapter_read: Got -2 bytes of message from MGMTD Frontend adapter 'mgmtd-7805'
2021/10/27 16:01:23 MGMTD: [XKZ2G-VEJPH] mgmt_frntnd_adapter_read: Got message (len: 22) from client 'mgmtd-7805'
2021/10/27 16:01:23 MGMTD: [RJJKW-SGDZB] mgmt_frntnd_adapter_proc_msgbufs: Have 1 ibufs for client 'mgmtd-7805' to process
2021/10/27 16:01:23 MGMTD: [T5DQJ-R96CZ] mgmt_frntnd_adapter_process_msg: Have 22 bytes of messages from client 'mgmtd-7805' to process
2021/10/27 16:01:23 MGMTD: [ZDW3N-JS2KM] mgmt_frntnd_adapter_process_msg: Decoded 22 bytes of message(type: 4/5) from MGMTD Frontend adapter 'mgmtd-7805'
2021/10/27 16:01:23 MGMTD: [XPYXA-6X0CB] mgmt_frntnd_adapter_handle_msg: Got LockDB Req Msg for DB:2 for session-id 14b023427490 from 'mgmtd-7805'
2021/10/27 16:01:23 MGMTD: [WZ8KX-NG91E] mgmt_frntnd_session_write_lock_db: Write-Locked the DB 2 for Sessn: 0x14b023427490 from mgmtd-7805!
2021/10/27 16:01:23 MGMTD: [XEKF7-AK9RY] mgmt_frntnd_send_lockdb_reply: Sending LOCK_DB_REPLY message to MGMTD Frontend client 'mgmtd-7805'
2021/10/27 16:01:23 MGMTD: [KH9NG-X1Z5V] mgmt_frntnd_session_handle_lockdb_req_msg: Failed to send LOCK_DB_REPLY for DB 2 Sessn: 0x14b023427490 from mgmtd-7805
2021/10/27 16:01:23 MGMTD: [X31CA-MCH7G] mgmt_frntnd_adapter_write: Wrote 24 bytes of message to MGMTD Frontend client socket.'
2021/10/27 16:01:23 MGMTD: [Y3TVX-KE7HN] Locked DB 2 successfully!
2021/10/27 16:01:26 MGMTD: [SD07F-GYBSK] mgmt_frntnd_adapter_read: Got 122 bytes of message from MGMTD Frontend adapter 'mgmtd-7805'
2021/10/27 16:01:26 MGMTD: [SD07F-GYBSK] mgmt_frntnd_adapter_read: Got -2 bytes of message from MGMTD Frontend adapter 'mgmtd-7805'
2021/10/27 16:01:26 MGMTD: [XKZ2G-VEJPH] mgmt_frntnd_adapter_read: Got message (len: 122) from client 'mgmtd-7805'
2021/10/27 16:01:26 MGMTD: [RJJKW-SGDZB] mgmt_frntnd_adapter_proc_msgbufs: Have 1 ibufs for client 'mgmtd-7805' to process
2021/10/27 16:01:26 MGMTD: [T5DQJ-R96CZ] mgmt_frntnd_adapter_process_msg: Have 122 bytes of messages from client 'mgmtd-7805' to process
2021/10/27 16:01:26 MGMTD: [ZDW3N-JS2KM] mgmt_frntnd_adapter_process_msg: Decoded 122 bytes of message(type: 11/11) from MGMTD Frontend adapter 'mgmtd-7805'
2021/10/27 16:01:26 MGMTD: [VXPEF-B0ZPP] mgmt_frntnd_adapter_handle_msg: Got Get-Config Req Msg for DB:2 (xpaths: 1) on session-id 22746738357392 from 'mgmtd-7805'
2021/10/27 16:01:26 MGMTD: [VZ3F2-245JH] mgmt_trxn_create_new: Added new 'SHOW' MGMTD Transaction '0x14b02342adf0'
2021/10/27 16:01:26 MGMTD: [M47CN-BCEGV] mgmt_trxn_lock: mgmtd/mgmt_trxn.c:2170 --> Lock SHOW Trxn 0x14b02342adf0, Count: 1
2021/10/27 16:01:26 MGMTD: [NNGJK-ZZQMQ] mgmt_frntnd_session_handle_getcfg_req_msg: Created new Show Trxn 0x14b02342adf0 for session 0x14b023427490
2021/10/27 16:01:26 MGMTD: [WTH61-T2ACQ] mgmt_trxn_req_alloc: Added a new GETCFG Req: 0x14b02342a950 for Trxn: 0x14b02342adf0, Sessn: 0x14b023427490
2021/10/27 16:01:26 MGMTD: [M47CN-BCEGV] mgmt_trxn_lock: mgmtd/mgmt_trxn.c:498 --> Lock SHOW Trxn 0x14b02342adf0, Count: 2
2021/10/27 16:01:26 MGMTD: [HNB4H-0BCVG] mgmt_trxn_send_get_config_req: XPath: '/frr-routing:routing/control-plane-protocols/control-plane-protocol[type='frr-staticd:staticd''
2021/10/27 16:01:26 MGMTD: [XPR3S-0G9BB] mgmt_trxn_process_get_cfg: Processing 1 GET_CONFIG requests for Trxn:0x14b02342adf0 Session:0x14b023427490
2021/10/27 16:01:26 MGMTD: [V2ZVT-01ZYY] mgmt_trxn_get_config: Trying to get all data under '/frr-routing:routing/control-plane-protocols/control-plane-protocol[type='frr-staticd:staticd''
2021/10/27 16:01:26 MGMTD: [NPDS4-978B5] mgmt_db_iter_data:  -- START DB walk for DBid: 2
2021/10/27 16:01:26 MGMTD: [QM1XN-1YM7F] mgmt_walk_db_nodes:  -- START: Base: /frr-routing:routing/control-plane-protocols/control-plane-protocol[type='frr-staticd:staticd'
2021/10/27 16:01:26 MGMTD: libyang: Unexpected XPath expression end.
2021/10/27 16:01:26 MGMTD: lib/yang.c:405: yang_dnode_get(): assertion (0) failed
MGMTD: Received signal 6 at 1635375686 (si_addr 0x6700001e7e, PC 0x73ed92034e97); aborting...
MGMTD: /usr/lib/x86_64-linux-gnu/frr/libfrr.so.0(zlog_backtrace_sigsafe+0x6d) [0x73ed92dac16d]
MGMTD: /usr/lib/x86_64-linux-gnu/frr/libfrr.so.0(zlog_signal+0xf3) [0x73ed92dac363]
MGMTD: /usr/lib/x86_64-linux-gnu/frr/libfrr.so.0(+0xd55b1) [0x73ed92ddb5b1]
MGMTD: /lib/x86_64-linux-gnu/libpthread.so.0(+0x12890) [0x73ed923f9890]
MGMTD: /lib/x86_64-linux-gnu/libc.so.6(gsignal+0xc7) [0x73ed92034e97]
MGMTD: /lib/x86_64-linux-gnu/libc.so.6(abort+0x141) [0x73ed92036801]
MGMTD: /usr/lib/x86_64-linux-gnu/frr/libfrr.so.0(_zlog_assert_failed+0xe9) [0x73ed92e06ce9]
MGMTD: /usr/lib/x86_64-linux-gnu/frr/libfrr.so.0(+0xf1f64) [0x73ed92df7f64]
MGMTD: /usr/lib/frr/mgmtd(+0x21494) [0x14b0214ab494]
MGMTD: /usr/lib/frr/mgmtd(mgmt_db_iter_data+0x164) [0x14b0214acba4]
MGMTD: /usr/lib/frr/mgmtd(+0x1e25a) [0x14b0214a825a]
MGMTD: /usr/lib/frr/mgmtd(+0x1e6d5) [0x14b0214a86d5]
MGMTD: /usr/lib/x86_64-linux-gnu/frr/libfrr.so.0(thread_call+0x7d) [0x73ed92debe4d]
MGMTD: /usr/lib/x86_64-linux-gnu/frr/libfrr.so.0(frr_run+0xe8) [0x73ed92da50f8]
MGMTD: /usr/lib/frr/mgmtd(main+0x12e) [0x14b02149cb5e]
MGMTD: /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x73ed92017b97]
MGMTD: /usr/lib/frr/mgmtd(_start+0x2a) [0x14b02149ceda]
MGMTD: in thread mgmt_trxn_process_get_cfg scheduled from mgmtd/mgmt_trxn.c:2253 mgmt_trxn_register_event()
2021/10/27 16:01:26 STATIC: [MHW97-3MX3F] mgmt_bcknd_client_read: ERROR: Got error (0) while reading from MGMTD Backend server. Err: 'Resource temporarily unavailable'
2021/10/27 16:01:26 STATIC: [PCNJ6-261A0] Got disconnected from MGMTD Backend Client Server
2021/10/27 16:01:29 STATIC: [YDHD2-AEB3Z] mgmt_bcknd_server_connect: ERROR: Failed to connect to MGMTD Backend Server at /var/run/frr/mgmtd_bcknd.sock. Err: Connection refused
2021/10/27 16:01:29 STATIC: [PCNJ6-261A0] Got disconnected from MGMTD Backend Client Server
2021/10/27 16:01:32 STATIC: [PCNJ6-261A0] Got connected to MGMTD Backend Client Server
2021/10/27 16:01:32 STATIC: [REJRT-8HBY1] Got Trxn DESTROY Notify from MGMTD server
2021/10/27 16:01:32 STATIC: [REJRT-8HBY1] Got Trxn CREATE Notify from MGMTD server
root@frr:/home/naveen/ci/mgmt_auto/frr/tests/topotests/yang_mgmt#

**Comment by pushpasis** [comment]
@gpnaveen This is fixed as far as I remember. Can you please check this on latest build and close if found fixed.

**Comment by pushpasis** [comment]
Closing it for now. Reopen if still seen.
